### ISSUE TITLE
Idea: encoding state information in state ID

### ISSUE THREAD

**Issue by klauer** [pcdshub/pmps-dev#1]
@ZLLentz, @teddyrendahl and I were discussing the following yesterday.

Background
------------
Currently, the only requirement for state IDs is that they are globally unique. To make them simply random or `[device id][arbitrary state number]` would be wasteful as we can encode a good amount of information in a 64-bit unsigned integer (`LWORD`).

Proposal
---------
Making the following assumptions:
* Less than 16,384 devices throughout the life of PMPS (14 bits)
* Maximum photon energy range 0-32keV (25keV in actuality) with 1eV resolution (15 bits)
* Transmission - 1% resolution (7 bits)
* Beam class - 16 options (4 bits)

We could have something like:
`[Device/14] [Transmission/7] [Beam class/4] [min eV/15] [max eV/15] [reserved/9]`
55 bits of useful information, with 9 to spare.

Support in TC3
---------------
Beckhoff does not appear to support C-style bit fields which would allow for easy packing of this data, but we can still make up a supporting set of functions to do it for us.

**Comment by ZLLentz** [comment]
Note that TC3 hash tables are stuck at 32 bit. An alternate, more compact packing may be something like:
`[Device/12][PositionId/4][Charge/8][ev/8]`
Including the position id (e.g. OUT, YAG) is important because it's the most basic field we'd use to construct the state.
